FROM ubuntu:16.04
MAINTAINER Roman

RUN apt-get update
RUN apt install -y nginx
RUN apt install -y php-fpm
COPY ./example.com /etc/nginx/sites-available/example.com
COPY ./info.php /var/www/html/info.php
RUN ln -s /etc/nginx/sites-available/example.com /etc/nginx/sites-enabled/
RUN unlink /etc/nginx/sites-enabled/default

EXPOSE 80

CMD service php7.0-fpm start && nginx -g "daemon off;"
